/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Video } from "./Video";
import { VideoCountArgs } from "./VideoCountArgs";
import { VideoFindManyArgs } from "./VideoFindManyArgs";
import { VideoFindUniqueArgs } from "./VideoFindUniqueArgs";
import { CreateVideoArgs } from "./CreateVideoArgs";
import { UpdateVideoArgs } from "./UpdateVideoArgs";
import { DeleteVideoArgs } from "./DeleteVideoArgs";
import { AnalyticsFindManyArgs } from "../../analytics/base/AnalyticsFindManyArgs";
import { Analytics } from "../../analytics/base/Analytics";
import { YouTubeChannel } from "../../youTubeChannel/base/YouTubeChannel";
import { VideoService } from "../video.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Video)
export class VideoResolverBase {
  constructor(
    protected readonly service: VideoService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Video",
    action: "read",
    possession: "any",
  })
  async _videosMeta(
    @graphql.Args() args: VideoCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Video])
  @nestAccessControl.UseRoles({
    resource: "Video",
    action: "read",
    possession: "any",
  })
  async videos(@graphql.Args() args: VideoFindManyArgs): Promise<Video[]> {
    return this.service.videos(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Video, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Video",
    action: "read",
    possession: "own",
  })
  async video(
    @graphql.Args() args: VideoFindUniqueArgs
  ): Promise<Video | null> {
    const result = await this.service.video(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Video)
  @nestAccessControl.UseRoles({
    resource: "Video",
    action: "create",
    possession: "any",
  })
  async createVideo(@graphql.Args() args: CreateVideoArgs): Promise<Video> {
    return await this.service.createVideo({
      ...args,
      data: {
        ...args.data,

        youtubeChannel: args.data.youtubeChannel
          ? {
              connect: args.data.youtubeChannel,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Video)
  @nestAccessControl.UseRoles({
    resource: "Video",
    action: "update",
    possession: "any",
  })
  async updateVideo(
    @graphql.Args() args: UpdateVideoArgs
  ): Promise<Video | null> {
    try {
      return await this.service.updateVideo({
        ...args,
        data: {
          ...args.data,

          youtubeChannel: args.data.youtubeChannel
            ? {
                connect: args.data.youtubeChannel,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Video)
  @nestAccessControl.UseRoles({
    resource: "Video",
    action: "delete",
    possession: "any",
  })
  async deleteVideo(
    @graphql.Args() args: DeleteVideoArgs
  ): Promise<Video | null> {
    try {
      return await this.service.deleteVideo(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Analytics], { name: "analyticsItems" })
  @nestAccessControl.UseRoles({
    resource: "Analytics",
    action: "read",
    possession: "any",
  })
  async findAnalyticsItems(
    @graphql.Parent() parent: Video,
    @graphql.Args() args: AnalyticsFindManyArgs
  ): Promise<Analytics[]> {
    const results = await this.service.findAnalyticsItems(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => YouTubeChannel, {
    nullable: true,
    name: "youtubeChannel",
  })
  @nestAccessControl.UseRoles({
    resource: "YouTubeChannel",
    action: "read",
    possession: "any",
  })
  async getYoutubeChannel(
    @graphql.Parent() parent: Video
  ): Promise<YouTubeChannel | null> {
    const result = await this.service.getYoutubeChannel(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
