/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { YouTubeChannelService } from "../youTubeChannel.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { YouTubeChannelCreateInput } from "./YouTubeChannelCreateInput";
import { YouTubeChannel } from "./YouTubeChannel";
import { YouTubeChannelFindManyArgs } from "./YouTubeChannelFindManyArgs";
import { YouTubeChannelWhereUniqueInput } from "./YouTubeChannelWhereUniqueInput";
import { YouTubeChannelUpdateInput } from "./YouTubeChannelUpdateInput";
import { VideoFindManyArgs } from "../../video/base/VideoFindManyArgs";
import { Video } from "../../video/base/Video";
import { VideoWhereUniqueInput } from "../../video/base/VideoWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class YouTubeChannelControllerBase {
  constructor(
    protected readonly service: YouTubeChannelService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: YouTubeChannel })
  @nestAccessControl.UseRoles({
    resource: "YouTubeChannel",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createYouTubeChannel(
    @common.Body() data: YouTubeChannelCreateInput
  ): Promise<YouTubeChannel> {
    return await this.service.createYouTubeChannel({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [YouTubeChannel] })
  @ApiNestedQuery(YouTubeChannelFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "YouTubeChannel",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async youTubeChannels(
    @common.Req() request: Request
  ): Promise<YouTubeChannel[]> {
    const args = plainToClass(YouTubeChannelFindManyArgs, request.query);
    return this.service.youTubeChannels({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: YouTubeChannel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "YouTubeChannel",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async youTubeChannel(
    @common.Param() params: YouTubeChannelWhereUniqueInput
  ): Promise<YouTubeChannel | null> {
    const result = await this.service.youTubeChannel({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: YouTubeChannel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "YouTubeChannel",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateYouTubeChannel(
    @common.Param() params: YouTubeChannelWhereUniqueInput,
    @common.Body() data: YouTubeChannelUpdateInput
  ): Promise<YouTubeChannel | null> {
    try {
      return await this.service.updateYouTubeChannel({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: YouTubeChannel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "YouTubeChannel",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteYouTubeChannel(
    @common.Param() params: YouTubeChannelWhereUniqueInput
  ): Promise<YouTubeChannel | null> {
    try {
      return await this.service.deleteYouTubeChannel({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/videos")
  @ApiNestedQuery(VideoFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Video",
    action: "read",
    possession: "any",
  })
  async findVideos(
    @common.Req() request: Request,
    @common.Param() params: YouTubeChannelWhereUniqueInput
  ): Promise<Video[]> {
    const query = plainToClass(VideoFindManyArgs, request.query);
    const results = await this.service.findVideos(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        id: true,
        title: true,
        updatedAt: true,

        youtubeChannel: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/videos")
  @nestAccessControl.UseRoles({
    resource: "YouTubeChannel",
    action: "update",
    possession: "any",
  })
  async connectVideos(
    @common.Param() params: YouTubeChannelWhereUniqueInput,
    @common.Body() body: VideoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      videos: {
        connect: body,
      },
    };
    await this.service.updateYouTubeChannel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/videos")
  @nestAccessControl.UseRoles({
    resource: "YouTubeChannel",
    action: "update",
    possession: "any",
  })
  async updateVideos(
    @common.Param() params: YouTubeChannelWhereUniqueInput,
    @common.Body() body: VideoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      videos: {
        set: body,
      },
    };
    await this.service.updateYouTubeChannel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/videos")
  @nestAccessControl.UseRoles({
    resource: "YouTubeChannel",
    action: "update",
    possession: "any",
  })
  async disconnectVideos(
    @common.Param() params: YouTubeChannelWhereUniqueInput,
    @common.Body() body: VideoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      videos: {
        disconnect: body,
      },
    };
    await this.service.updateYouTubeChannel({
      where: params,
      data,
      select: { id: true },
    });
  }
}
